### ISSUE TITLE
Error: recording error!

### ISSUE THREAD

**Issue by mjuarezm** [dbermond/screencast#10] opened 2020-07-29 18:22 UTC
I'm able to run `screencast` but when I send a signal with Ctrl+C to stop recording I get this error:

```
Exiting normally, received signal 2.
[ screencast ] error: recording error!
```
The command I use is:  `screencast --display=:1 output.mp4`

How can I debug this error? Thank you.

**Comment by dbermond** [comment] 2020-07-29 20:15
This is expected and is not a screencast error.

As described in the [examples](https://github.com/dbermond/screencast/tree/v1.5.0#examples) section, you should terminate the recording by pressing the `q` key. You can also use the [`-x`/`--fixed`](https://github.com/dbermond/screencast/tree/v1.5.0#-x---fixedn) option if you need to record for a fixed (predetermined) period of time.

Do not use Ctrl+C to terminate the recording.

When you press Ctrl+C, ffmpeg exits with an error return code (non-zero return code), and this is interpreted by screencast as if an error has occurred during the recording.

**Comment by dbermond** [comment] 2020-09-19 23:01
Closing this since, as explained, it's the expected behavior and not a bug.

**Closed as completed by dbermond** 2020-09-19 23:01 UTC
Labels: invalid, not-a-bug
